- hosts: all
  become: true
  pre_tasks:
  - name: apt update
    apt:
      update_cache: true
  roles:
    - role: ansible
    - role: git
    - role: jq
    - role: docker
    - role: vscode
    - role: golang
    - role: virtualbox
    - role: vagrant
    - role: nodejs
    - role: vim
    - role: google-chrome
    - role: python
