- name: download .deb package
  get_url:
    url: https://go.microsoft.com/fwlink/?LinkID=760868
    dest: /home/ubuntu/Downloads
    mode: 664
  register: vscode
- name: install vscode
  apt:
    deb: "{{ vscode.dest }}"
    force: true
- name: upgrade vscode
  apt:
    name: code
    state: latest
