Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.11"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
    ansible.extra_vars = { 
      ansible_ssh_user: 'vagrant',
      ansible_python_interpreter: '/usr/bin/python3'
    }
  end

end
