- name: update apt for ubuntu
  block:
  - name: add apt-key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
  - name: update package repository
    apt_repository:
      repo: deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
      state: present
  when: (ansible_facts['lsb']['codename'] == 'xenial') or (ansible_facts['lsb']['codename'] == 'bionic')
- name: install oracle virtualbox
  apt:
    name: virtualbox-{{ virtualbox.version }}
    update_cache: true
    state: present
