- name: Remove old version
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker
    - docker-engine
    - docker.io
- name: Install Packages
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Verify fingerprint
  apt_key:
    id: "{{ docker.fingerprint }}"
- name: Define lsb_release -cs
  shell: lsb_release -cs
  changed_when: no
  register: lsb_release
- name: Setup stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
    state: present
- name: Install docker-ce
  apt:
    name: docker-ce
    state: present

#docker without sudo
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
- name: add user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    group: docker
